
import type { Metadata } from 'next'
import './globals.css'
import { montserrat } from './fonts'


export const metadata: Metadata = {
  title: 'Dannybell Restaurante',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>{children}</body>
    </html>
  )
}